#+title: Mohabat Tarkeshian (1994 - 2024)

Mohabat Tarkeshian was a wonderful, kind and caring person who unexpected passed away at the young age of 29 in April 2024. She was many things - a great mathematician; a good friend; a fantastic listener and a very hard worker. To me, she was my best friend and my fiancée.

I had the great fortune to meet Mohabat when we both started our Ph.D programmes at The University of Western Ontario in September 2019. We shared an office together and became quick friends, bonding over our mutual enjoyment mathematical problems, good coffee and conversations about philosophy and psychology. I think that we were both drawn to each other from the moment we met, and we only grew closer as time went on.

Mohabat and I became closer while we were revising for our Algebra comprehensive exams. I would regularly challenge her to a race to see which one of us could compute the Galois group of a certain field extension first, and Mohabat would always have a clean and correct solution before I did. Whilst this was going on, we were both experiencing Ontario's second Covid 19 lockdown so meeting each other was not an option. We did enjoy many Zoom dates together, where we would catch up and watch some episodes of It's Always Sunny in Philadelphia. She would be in tears laughing at some of the jokes on the show. The two of us looked back fondly on these times, as we knew it was the start of our love for one another.

At the start of 2021, my PhD fell through and I left the programme. The most heartbreaking part was the knowledge that I would have to go back to the United Kingdom at some point and be separated from Mohabat. We made the most of our year together, going on some nice trips Niagara Falls and Tobermory, to name a few, with friends. Early on in this year, Mohabat accomplished one of her life long dreams of having a dog. Woody (the Chocolate Labrador) was a key part of Mohabat's life. He provided Mohabat with support; happiness; and the type of friendship you can only get from a dog, during some of the hardest and most stressful years of her life.

Despite moving back to the United Kingdom at the start of 2022, Mohabat and I continued our relationship and were determined to make it work through the distance. It wasn't easy for either of us, but we did our best. With the help and support of Mohabat, I started a new job. Mohabat continued to excel at her work and progress through her PhD programme. I took every opportunity to go and visit her and Woody that I could; both of us cherished the short times that we were together on the same continent.

I will always remember the summer of 2022 fondly as it was the summer that Mohabat and I visited Europe together. We stayed in Montpelier for a week so that she could attend The International Colloquium on Graph Theory and Combinatorics. The main highlight for me was the afternoon we spent relaxing together on the shore in the sun. We spent two months together, mostly where I was working in England, but also in the town I grew up in, in Scotland.

In 2023, Mohabat completed her PhD and began her new career as Assistant Professor at The University of St Francis Xavier, in Antigonish, Nova Scotia. There, she made lots of friends and made wonderful impressions on her many students. On New Years eve, she accepted my proposal and we entered the new year as fiancés.

On the morning of April 27th, while the two of us were out of a dog walk, Mohabat collapsed and was rushed to hospital. There, she passed away, surrounded both love from both me and her family.

Mohabat changed my life, and the lives of those she met, for the better. She was my best friend, and my heart aches in her absence. I know that the main thing she would want now is for Woody to be taken care of, which I am doing my best to do. I strive to keep her alive by embodying the kindness and warmth that she shared with everyone she met.
 -----

Mohabat gained many awards during her time as a student. We kept an up to date list of them on her website, found [[https://mohabatmath.ca][here]].
