#+title: Is zero a natural number?
#+author: James Leslie
#+date: 2019-04-15
#+options: tex:t

I help tutor an introductory course on pure mathematics at Edinburgh University. One my responsibilities is to help answer questions that the students have in person and online on Piazza; a Q&A forum used by the class. The other day, a student created a poll asking whether or not zero is a natural number. I have found that this question usually always splits the audience, with a majority usually favouring "no" as the correct answer. I remember the first time I came across this debate was during my final year of high school, when our teacher described the "home of zero" as a controversial topic. At that time, for no legitimate reason, I chose to believe that it should be a natural number and this choice has more or less stuck with me till this day. Being a student of pure mathematics, it does strike me as an odd that this causes such a debate. Having the natural numbers with or without zero doesn't affect mathematics in the slightest; we can simply define a new set to be the naturals with or without zero.

When debating against zero being natural, more often than not, one will make some form of an appeal to tradition. Usually, it goes something like: "people thought up and used other natural numbers before coming up with the concept of zero, so it is not natural". I personally don't think this is a good argument as we don't follow conventions from the past blindly; they can be updated and changed if necessary. A better (and also common) argument is that the naturals are used for counting. By starting our counting system at 1, the set \( \{1, 2, \ldots, n \}\) contains exactly \( n\) elements, while if treat \( 0\) as the start, then the set of elements up to \( n\) will have cardinality \( n+1\). If you have \( n\) objects, it seems more natural to put them in a bijection in the following way, your first object is identified with \( 1\), your second with \( 2\) and so on. This idea comes from treating the naturals just as an ordered set. There is no need for something to come before the object that we call /first/, and if there was, our language would arguably be nefarious. 

I think the most compelling argument for including zero in the natural numbers is from how the naturals are constructed through Peano's axioms. Simply, one starts with \( 0\) and applies a successor operation, \( S\) to it. This gives a new term \( S0\) which we treat as being distinct from \( 0\), by some of Peano's other axioms. We then define \( 1:= S0\), and in general define \( n:= S(n-1)\). Peano's axioms; however, don't construct a set, per se, but a /Peano Structure/. By saying this is not a set, I mean in the same sense that a group is not a set, but a set with structure, not that it forms a proper class. There are many different Peano structures, but the naturals with \( 0\) and the usual successor function, \( - + 1\) satisfy a nice universal property. We can define a category whose objects are (set based) Peano structures, that is, triples \( (X, S:X \rightarrow X, a \in X)\) and whose maps \( f: (X, S, a) \rightarrow (Y, S', b)\) are functions \( f:X \rightarrow Y\) that make the following commute:

\begin{tikzcd} 1 \ar[r, "a"] \ar[rd, "b"'] & X \ar[r, "S"] \ar[d, "f"] & X \ar[d, "f"] \\
 & Y \ar[r, "S'"'] & Y\end{tikzcd}

The universal property satisfied by \( (\mathbb{N}, S, 0)\) is that it is initial in this category, that is, given any other object \( (Y, S', b \in Y)\), there is a unique map \( f: (\mathbb{N}, S, 0) \rightarrow (Y, S', b )\). This effectively is what lets us define functions recursively. From a category theory perspective, \( 0:1 \rightarrow \mathbb{N}\) is a generalised element of \( \mathbb{N}\). However, we could equally define an isomorphic copy of our initial Peano structure by swapping some symbols around and renaming our generalised element "0" as "1". Then, applying the obvious forgetful functor we can get something that looks like a natural number object, but starts at 1. This leads me to a critique of most arguments about the naturality of zero: mostly the argument revolves around what it means to be a natural number, when really it should be based on what it means to be /zero./ 

When speaking in terms of sets, the only difference between the naturals with or without zero, is what we call the elements. As a set, the element \( 0 \in \mathbb{N}\) can be interpreted to be any element we want, precisely because there is no structure on a set. If we were feeling perverse, we could say that \( 0+1 = 7\), simply by interpreting the symbols differently. It is when we add certain structure that the notion of zero becomes necessary. If we are needing an additive identity then the natural numbers begin to resemble a monoid and hence should be taken to include a zero. Are we simply counting objects or treating the naturals as an ordered set? Then there is no need for the additive identity, so the first element should probably be \( 1\).

So is zero a natural number? In my opinion, that depends on the problem you are working on. I think the reason that most people say that zero is not part of the naturals, is due to them thinking of the naturals as being an ordered set. This concept is taught much earlier in people's lives than the idea of a monoid, or just the notion of an identity. This debate won't be over any time soon, but hopefully people can start understanding the other side of the debate and see that both notions of the natural numbers make sense in their given context.

