---
title: iPad Screen Sharing to Zoom on a University Network
author: James Leslie
---
#+title: iPad Screen Sharing to Zoom on a University Network
#+OPTIONS: tex:nil num:nil toc:nil
#+date:<2021-03-05 Fri>

I am currently a teaching assistant for a first year linear algebra course. We recently made the switch to a hybrid setup, meaning that I am streaming the tutorials on Zoom as well as talking to a class in-person. Instead of writing on the physical whiteboards in the classroom, I instead write on my iPad and share the screen through Zoom. Previously, when the tutorials were just based on Zoom, this setup worked pretty well - I can share my screen over Zoom using my home WiFi network. However, I can't screen share over the university network due to the way it is set up.

* Solution 1
The basic solution is to log into the Zoom call on the iPad, and share the screen through the Zoom app. This is less than ideal, however; as it means that if you haven't turned off notifications, they can be displayed to the class. Also, I use the app GoodNotes to write my solutions on. The app is good, but there is a large header of different pen options that takes up too much space for my liking. This header is not shown when sharing content to Zoom over the network, rather than through the IPad.

* Solution 2
The current solution I use works on Windows 10 laptops. Windows 10 has the functionality to be connected to a network whilst also being a WiFi hotspot. Information on how to enable this can be found [[https://support.microsoft.com/en-us/windows/use-your-pc-as-a-mobile-hotspot-c89b0fad-72d5-41e8-f7ea-406ad9036b85][here]]. Once the hotspot is up and running, we can connect the iPad to the network. Then, Zoom can detect the IPad, and we can share content over this network. So far, this has worked well for me. The only caveat is that it seems like you can't get access to the internet on the IPad whilst connected to the network. This isn't a major problem for me, as I still have access through my laptop.

This setup might work for other operating systems, but I am not able to test that theory out.
